"""initial schema

Revision ID: facf3c46882f
Revises:
Create Date: 2026-10-09 19:02:03.434081

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'facf3c46882f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('company_domain', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('first_contact_at', sa.DateTime(), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('last_event_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_company_domain', 'applications', ['company_domain'], unique=False)
    op.create_table('mail_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('credentials_ref', sa.Text(), nullable=True),
    sa.Column('last_sync_cursor', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('is_job_related', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'provider_message_id', name='uq_account_message')
    )
    op.create_index('ix_emails_is_job_related', 'emails', ['is_job_related'], unique=False)
    op.create_index('ix_emails_received_at', 'emails', ['received_at'], unique=False)
    op.create_index('ix_emails_thread_id', 'emails', ['thread_id'], unique=False)
    op.create_table('application_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('interview_at', sa.DateTime(), nullable=True),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_application_id', 'application_events', ['application_id'], unique=False)
    op.create_index('ix_events_event_date', 'application_events', ['event_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_event_date', table_name='application_events')
    op.drop_index('ix_events_application_id', table_name='application_events')
    op.drop_table('application_events')
    op.drop_index('ix_emails_thread_id', table_name='emails')
    op.drop_index('ix_emails_received_at', table_name='emails')
    op.drop_index('ix_emails_is_job_related', table_name='emails')
    op.drop_table('emails')
    op.drop_table('mail_accounts')
    op.drop_index('ix_applications_company_domain', table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
